## Minimal TF model for XOR

Let's try to build the minimal model for a XOR function, using TensorFlow.

In [1]:
import tensorflow as tf
import numpy as np

Let's define the train data. We use the entire XOR table, with no validation. We will overfit, but it should not be a problem here.

In [2]:
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([    0,      1,      1,      0 ])

Since the examples are not linearly separable, we cannot use just one neuron. Hence, let's create an intermediate layer of the minimum 2 neurons needed to add a nonlinearity

In [3]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(2, input_shape=(2,), activation="relu", use_bias=False),
  tf.keras.layers.Dense(1, activation='sigmoid')
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 4         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 7
Trainable params: 7
Non-trainable params: 0
_________________________________________________________________


Compile the model. As lost function we use cross entropy and we are computing the accuracy metric.

In [4]:
model.compile(loss='binary_crossentropy', metrics=['accuracy'])

Fit the model on the data (train the model)

In [5]:
model.fit(x, y, epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6170 - accuracy: 0.7500
Epoch 2/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6163 - accuracy: 0.7500
Epoch 3/200
1/1 [==============================] - 0s 1ms/step - loss: 0.6158 - accuracy: 0.7500
Epoch 4/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6153 - accuracy: 0.7500
Epoch 5/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6150 - accuracy: 0.7500
Epoch 6/200
1/1 [==============================] - 0s 1ms/step - loss: 0.6146 - accuracy: 0.7500
Epoch 7/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6143 - accuracy: 0.7500
Epoch 8/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6140 - accuracy: 0.7500
Epoch 9/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6137 - accuracy: 0.7500
Epoch 10/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6135 - accuracy: 0.7500
Epoch 11/200
1/1 [===========

Take the predictions of the model:

In [6]:
model(x)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.47052434],
       [0.6932425 ],
       [0.5442231 ],
       [0.39172065]], dtype=float32)>

Assume that everything above 0.5 is True, convert to output of XOR gate.

In [7]:
(model.predict(x) > 0.5)

array([[False],
       [ True],
       [ True],
       [False]])

That's all. Thank you